#!/bin/bash
#
# Builds the project in the continuous integration environment.
#
set -o nounset -o errexit

echo ""
echo "Compiling"
scripts/sbt clean compile test:compile

echo ""
echo "Validating code formatting"
scripts/validate-format

echo ""
echo "Testing and generating documentation"
scripts/sbt -v coveralls doc

echo ""
echo "Build finished"
echo ""
