#!/bin/bash
#
# Builds the project in the continuous integration environment.
#
# Copyright 2015 Mohiva Organisation (license at mohiva dot com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -o nounset -o errexit

echo ""
echo "Compiling"
scripts/sbt clean compile test:compile

echo ""
echo "Validating code formatting"
scripts/validate-format

echo ""
echo "Testing and generating documentation"
scripts/sbt coverage test doc && scripts/sbt coverageAggregate

echo ""
echo "Build finished"
echo ""
